imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

parameters:
    client_id: 'your_client_id'
    client_secret: 'your_client_secret'
    redirect_uri: 'http://localhost:8000/callback/artikcloud'
    device_type_id: 'dt013005c9302a428990073c9d6359b354'
    device_type_unique_name: 'cloud.artik.example.activitytracker'

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: 'php://stderr'
            level: debug
        console:
            type: console
